name: firstplugin
version: '${project.version}'
main: firstplugin.firstplugin.Firstplugin
api-version: '1.18'
commands:
  vlieg:
      description: laat je mooi vlieggen
      usage: /vlieg
      aliases:

  menu:
    description: opens menu
    usage: /menu